runtime: nodejs20

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"
  NODE_ENV: "production"
  APP_NAME: "TestMyEnglishOnline"
  PORT: "8000"
  CLIENT_URL: "https://test-my-english-online-frontend.vercel.app"
  DATABASE_CLOUD: "mongodb+srv://khoshow:HelloTest9876#@cluster0.ab2rpkm.mongodb.net/?retryWrites=true&w=majority"
  DATABASE_LOCAL: 'mongodb://0.0.0.0:27017/myEnglishTest'
  JWT_SECRET: "ugfyerwnbhxzcv74rn4jkxz79"
  SENDGRID_API_KEY: "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"
  EMAIL_TO: "khoshow.official@gmail.com"
  EMAIL_FROM: "khoshow.developer@gmail.com"
  JWT_RESET_PASSWORD: "034957439HIU34U43H034ORpidfeiutg1"
  JWT_ACCOUNT_ACTIVATION: "jhdsf78rtbjkzcs7ret90734r5ndsgf1"
  GOOGLE_CLIENT_ID: "180533803868-5udnafos7d5q7lp77dfgialchglkg1.apps.googleusercontent.com"
  CLOUDINARY_CLOUD_KEY: "dreunylt8"
  CLOUDINARY_API_KEY: "744668751588215"
  CLOUDINARY_SECRET_KEY:  "Cg9WCzT1yPTNf55UxXm0tF4VeE0"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto