runtime: nodejs20

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"
  NODE_ENV: "production"
  APP_NAME: "TestMyEnglishOnline"
  PORT: "8000"
  CLIENT_URL: "https://test-my-english-online-frontend.vercel.app"
  DATABASE_CLOUD: "mongodb+srv://khoshow:MyTest3456#@cluster0.ab2rpkm.mongodb.net/?retryWrites=true&w=majority"
  DATABASE_LOCAL: 'mongodb://0.0.0.0:27017/myEnglishTest'
  JWT_SECRET: "ugfyerwnbhxzcv74w5rn4jkxz79"
  SENDGRID_API_KEY: "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"
  EMAIL_TO: "khoshow.official@gmail.com"
  EMAIL_FROM: "khoshow.developer@gmail.com"
  JWT_RESET_PASSWORD: "034957439HIU34R9U43H034ORpidfiutg1"
  JWT_ACCOUNT_ACTIVATION: "jhdsf78rtbjkxgzcs7ret907345ndsgf1"
  GOOGLE_CLIENT_ID: "180533803868-5udnu3iptafos7d5q7lp77dialchglkg1.apps.googleusercontent.com"
  CLOUDINARY_CLOUD_KEY: "dreunylt8"
  CLOUDINARY_API_KEY: "774751474439835"
  CLOUDINARY_SECRET_KEY:  "OSkutPuVASCDoiy2a_EZpNQttQ0"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto